<?php
/**
 * UserDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserDataTest Class Doc Comment
 *
 * @category    Class
 * @description user_data is a set of identifiers Facebook can use for targeted attribution. You must provide at least one of the following user_data keys in your request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserData"
     */
    public function testUserData()
    {
    }

    /**
     * Test attribute "em"
     */
    public function testPropertyEm()
    {
    }

    /**
     * Test attribute "ph"
     */
    public function testPropertyPh()
    {
    }

    /**
     * Test attribute "ge"
     */
    public function testPropertyGe()
    {
    }

    /**
     * Test attribute "db"
     */
    public function testPropertyDb()
    {
    }

    /**
     * Test attribute "ln"
     */
    public function testPropertyLn()
    {
    }

    /**
     * Test attribute "fn"
     */
    public function testPropertyFn()
    {
    }

    /**
     * Test attribute "ct"
     */
    public function testPropertyCt()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "st"
     */
    public function testPropertySt()
    {
    }

    /**
     * Test attribute "zp"
     */
    public function testPropertyZp()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "client_ip_address"
     */
    public function testPropertyClientIpAddress()
    {
    }

    /**
     * Test attribute "client_user_agent"
     */
    public function testPropertyClientUserAgent()
    {
    }

    /**
     * Test attribute "fbc"
     */
    public function testPropertyFbc()
    {
    }

    /**
     * Test attribute "fbp"
     */
    public function testPropertyFbp()
    {
    }

    /**
     * Test attribute "subscription_id"
     */
    public function testPropertySubscriptionId()
    {
    }
}
